### ISSUE TITLE
Ranges, Content State, and the navPlace Property

### ISSUE THREAD

**Issue by markpbaggett** [CenterForDigitalHumanities/navplace-viewer#13]
Hello, I'm wondering about how navplace-viewer should render `navPlace` on a Range. I have a collection of objects that are oral histories. In the metadata for the collection, there are time-based cues that track when a particular geographic location is discussed.  The information from the metadata is leveraged and used to create a table of contents of sort as you can see [here](https://rfta.lib.utk.edu/interviews/object/seemona-and-daniel-whaley-2019-09-20) or below:

![image](https://user-images.githubusercontent.com/2692416/190705139-52d906c3-83dc-4e1e-a902-336c4151f1b5.png)

Since I already have this data, I thought it'd make sense to link the geographic data to the Range in addition to the Manifest via `navPlace`. When I load in  navplace-viewer, I am able to click on a point that represents a Feature in the Feature Collection of the navPlace property on the manifest, and get links / icons to open the object in UV or Mirador:

![image](https://user-images.githubusercontent.com/2692416/190705781-091d6bd3-8715-4061-94a1-c63fbafde2ac.png)

But when I click on the Range, I only get the label:

![image](https://user-images.githubusercontent.com/2692416/190705939-085b8cde-a49f-4dd0-baca-be99b51d4117.png)

In some ways, this makes sense.  As you can see in the [manifest](https://digital.lib.utk.edu/assemble/manifest/rfta/8), the Range has an `items` prop  with a part of the Canvas represented by a temporal media fragment. The URI for the part of the Canvas in the Range is not dereferenceable. The media fragment references an embedded Canvas on the Manifest that is also not dereferenceable.  My question:  how should navplace-viewer handle something like this if at all? Since this is a temporal media fragment on a canvas, it seems like if there was a link to UV or Mirador that it would need to be converted to a content state URL first and that seems like a big ask.

Let me know if you have any thoughts about this problem or questions about my use case in general.

**Comment by thehabes** [comment]
I do understand the questions and will boil it down to what choices are made in the code here which are simple to articulate.

Ranges are simply not considered when ensuring those links are available.  In code speak...

```javascript
if (feature.properties.manifest) {
    let manifestURI = feature.properties.manifest ?? ""
    popupContent += `<a href="https://projectmirador.org/embed/?iiif-content=${manifestURI}" target="_blank"><img src="https://www.qdl.qa/sites/all/themes/QDLTheme/css/img/logo_mirador.png"/></a>`
    popupContent += `<a href="https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=${manifestURI}" target="_blank"><img src="https://www.qdl.qa/sites/all/themes/QDLTheme/css/img/logo_uv.png"/></a>`
}
else if (feature.properties.canvas) {
    let canvasURI = feature.properties.canvas ?? ""
    popupContent += `<a href="https://projectmirador.org/embed/?iiif-content=${canvasURI}" target="_blank"><img src="https://www.qdl.qa/sites/all/themes/QDLTheme/css/img/logo_mirador.png"/></a>`
    popupContent += `<a href="https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=${canvasURI}" target="_blank"><img src="https://www.qdl.qa/sites/all/themes/QDLTheme/css/img/logo_uv.png"/></a>`
}
```
Notice is there is nothing the handle a `feature.properties.collection` or a `feature.properties.range`




**_This section is non-normative_**.  _There are no standards or IIIF contexts describing these properties.  They are internal so that each feature can track the URI of the resource is belongs to._

`properties.canvas` and `properties.manifest` either exist ahead of time or are programmatically generated so that each `resource.navPlace.feature[n]` knows the URI of the resource is belongs to.  As you can guess, I only do the programmatic generation of this property for Manifests and Canvases.

If desired, I can do the same thing for Collections and Ranges with a `properties.collection` and `properties.range` for each `Collection.navPlace.feature[n]` and each `Range.navPlace.feature[n]`.  It would be a small change.
