### ISSUE TITLE
Download to Local Machine

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/navplace-viewer#33]
This came up during the IIIF 2023 Annual Conference.  If the goal is to "have a resource to walk away with", that may not mean actually saving it into a database.  There should be an option to save to the client machine, which they can then alter and take with them to save it where they want to.

**Comment by glenrobson** [comment]
Hi Bryan, 

I can't remember if this is already possible but it would be great if you could provide the navPlace code in a copy and paste type environment so that users can locate their manifest and then copy the resulting navPlace into the JSON of their manifest. This would be useful for the training.

Thanks

**Comment by thehabes** [comment]
Moved to geo.rerum.io
